export default [
    {
        'name':'hat-1',
        'id': '01',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'hat',
    },
    {
        'name':'hat-2',
        'id': '02',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'hat',
    },
    {
        'name':'hat-3',
        'id': '03',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'hat',
    },
    {
        'name':'hat-4',
        'id': '04',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'hat',
    },
    {
        'name':'shirt-1',
        'id': '05',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'shirt',
    },
    {
        'name':'shirt-2',
        'id': '06',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'shirt',
    },
    {
        'name':'shirt-3',
        'id': '07',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'shirt',
    },
    {
        'name':'shirt-4',
        'id': '08',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'shirt',
    },
    {
        'name':'pants-1',
        'id': '09',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'pants',
    },
    {
        'name':'pants-2',
        'id': '10',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'pants',
    },
    {
        'name':'pants-3',
        'id': '11',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'pants',
    },
    {
        'name':'pants-4',
        'id': '12',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'pants',
    },
    {
        'name':'shoes-1',
        'id': '13',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'shoes',
    },
    {
        'name':'shoes-2',
        'id': '14',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'shoes',
    },
    {
        'name':'shoes-3',
        'id': '15',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'shoes',
    },
    {
        'name':'shoes-4',
        'id': '16',
        'image': './assets/hanger.png',
        'selected': false,
        'category': 'shoes',
    }
];