export default [

    {
        name: 'top-12',
        id: 3,
        image: 'tops12.jpg',
        selected: false,
        category: 'top',
        weather: 'warm',
    },
    {
        name: 'top-11',
        id: 4,
        image: 'tops11.jpg',
        selected: false,
        category: 'top',
        weather: 'cold',
    },
    {
        name: 'top-1',
        id: 5,
        image: 'tops01.jpg',
        selected: false,
        category: 'top',
        weather: 'warm',
    },
    {
        name: 'top-2',
        id: 6,
        image: 'tops02.jpg',
        selected: false,
        category: 'top',
        weather: 'warm',
    },
    {
        name: 'top-3',
        id: 7,
        image: 'tops03.jpg',
        selected: false,
        category: 'top',
        weather: 'cold',
    },
    {
        name: 'top-4',
        id: 8,
        image: 'tops04.jpg',
        selected: false,
        category: 'top',
        weather: 'cold',
    },
    {
        name: 'top-5',
        id: 9,
        image: 'tops05.jpg',
        selected: false,
        category: 'top',
        weather: 'cold',
    },
    {
        name: 'top-6',
        id: 10,
        image: 'tops06.jpg',
        selected: false,
        category: 'top',
        weather: 'warm',
    },
    {
        name: 'top-7',
        id: 11,
        image: 'tops07.jpg',
        selected: false,
        category: 'top',
        weather: 'warm',
    },
    {
        name: 'top-8',
        id: 12,
        image: 'tops08.jpg',
        selected: false,
        category: 'top',
        weather: 'cold',
    },
    {
        name: 'top-9',
        id: 13,
        image: 'tops09.jpg',
        selected: false,
        category: 'top',
        weather: 'cold',
    },
    {
        name: 'top-10',
        id: 14,
        image: 'tops10.jpg',
        selected: false,
        category: 'top',
        weather: 'warm',
    },
    {
        name: 'pants-1',
        id: 15,
        image: 'bottoms01.jpg',
        selected: false,
        category: 'pants',
        weather: 'cold',
    },
    {
        name: 'pants-2',
        id: 16,
        image: 'bottoms02.jpg',
        selected: false,
        category: 'pants',
        weather: 'cold',
    },
    {
        name: 'pants-3',
        id: 17,
        image: 'bottoms03.jpg',
        selected: false,
        category: 'pants',
        weather: 'warm',
    },
    {
        name: 'pants-4',
        id: 18,
        image: 'bottoms04.jpg',
        selected: false,
        category: 'pants',
        weather: 'warm',
    },
    {
        name: 'pants-5',
        id: 19,
        image: 'bottoms05.jpg',
        selected: false,
        category: 'pants',
        weather: 'warm',
    },
    {
        name: 'pants-6',
        id: 20,
        image: 'bottoms06.jpg',
        selected: false,
        category: 'pants',
        weather: 'cold',
    },
    {
        name: 'pants-7',
        id: 21,
        image: 'bottoms07.jpg',
        selected: false,
        category: 'pants',
        weather: 'warm',
    },
    {
        name: 'pants-8',
        id: 22,
        image: 'bottoms08.jpg',
        selected: false,
        category: 'pants',
        weather: 'cold',
    },
    {
        name: 'pants-9',
        id: 23,
        image: 'bottoms09.jpg',
        selected: false,
        category: 'pants',
        weather: 'warm',
    },
    {
        name: 'pants-10',
        id: 24,
        image: 'bottoms10.jpg',
        selected: false,
        category: 'pants',
        weather: 'warm',
    },
    {
        name: 'pants-11',
        id: 25,
        image: 'bottoms11.jpg',
        selected: false,
        category: 'pants',
        weather: 'cold',
    },
    {
        name: 'pants-12',
        id: 26,
        image: 'bottoms12.jpg',
        selected: false,
        category: 'pants',
        weather: 'warm',
    }
];