export default [
    {
        name:'hat-1',
        id: 1,
        image: 'hanger.png',
        selected: false,
        category: 'hat',
    },
    {
        name:'hat-2',
        id: 2,
        image: 'hanger.png',
        selected: false,
        category: 'hat',
    },
    {
        name:'hat-3',
        id: 3,
        image: 'hanger.png',
        selected: false,
        category: 'hat',
    },
    {
        name:'hat-4',
        id: 4,
        image: 'hanger.png',
        selected: false,
        category: 'hat',
    },
    {
        name:'shirt-1',
        id: 5,
        image: 'tops01.jpg',
        selected: false,
        category: 'shirt',
    },
    {
        name:'shirt-2',
        id: 6,
        image: 'hanger.png',
        selected: false,
        category: 'shirt',
    },
    {
        name:'shirt-3',
        id: 7,
        image: 'hanger.png',
        selected: false,
        category: 'shirt',
    },
    {
        name:'shirt-4',
        id: 8,
        image: 'hanger.png',
        selected: false,
        category: 'shirt',
    },
    {
        name:'pants-1',
        id: 9,
        image: 'hanger.png',
        selected: false,
        category: 'pants',
    },
    {
        name:'pants-2',
        id: 10,
        image: 'hanger.png',
        selected: false,
        category: 'pants',
    },
    {
        name:'pants-3',
        id: 11,
        image: 'hanger.png',
        selected: false,
        category: 'pants',
    },
    {
        name:'pants-4',
        id: 12,
        image: 'hanger.png',
        selected: false,
        category: 'pants',
    },
    {
        name:'shoes-1',
        id: 13,
        image: 'hanger.png',
        selected: false,
        category: 'shoes',
    },
    {
        name:'shoes-2',
        id: 14,
        image: 'hanger.png',
        selected: false,
        category: 'shoes',
    },
    {
        name:'shoes-3',
        id: 15,
        image: 'hanger.png',
        selected: false,
        category: 'shoes',
    },
    {
        name:'shoes-4',
        id: 16,
        image: 'hanger.png',
        selected: false,
        category: 'shoes',
    }
];